### ISSUE TITLE
有辦法使用GDB debug嗎？

### ISSUE THREAD

**Issue by XiaoLeS** [compiler-s20/discussion#73]
如圖，不知道助教所提供的docker中有沒有類似的工具可以使用呢？

**Comment by Naetw** [comment]
Hi, @XiaoLeS 

不好意思，助教忘記裝了 @@

剛剛已經更新 image (credit: @ianre657)，同學可以在 repo 底下重新下一次 `make docker-pull` 應該就會拿到新的 image，裡面會有 `gdb` 能夠使用。

**Comment by XiaoLeS** [comment]
感謝助教ＱＱＱＱ

**Comment by ianre657** [comment]
@XiaoLeS 

這是當初忘記加上去，未來如果有類似情況可以再回報
感謝

**Comment by singlexx5** [comment]
@ianre657  hello 助教. 你好
想要使用 gdb 來debug. 請問要怎麼找到 core file?

有出現以下的錯誤.
``` C
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
``` 
確認 ulimit  結果如以下
``` C
student@compiler-s20:~/src$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31748
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

```

目前docker image 版本為
```
docker image inspect ianre657/compiler-s20-hw3:latest
[
    {
        "Id": "sha256:5ae5afbe3b4bcba3399290d70f8bbcdbc189ab7b66b57c620bc2f300b7dc7210",
        "RepoTags": [
            "ianre657/compiler-s20-hw3:latest"
        ],
        "RepoDigests": [
            "ianre657/compiler-s20-hw3@sha256:fb06b07fc4cb58d80374bf2cecb50ce8df7041aafd88b40d0509728fc0e136f8"
        ],
```

卡了有點久  還是不得己麻煩你們 Q_Q .. 不好意思.

**Comment by iblis17** [comment]
系統不知道有沒有開 dump core 的行為

不過你可以直接在 gdb 裡面執行的 crash，再去看 bt

`gdb --args ./src/parser <file> --dump-ast`
之類的

**Comment by singlexx5** [comment]
感謝分享.   code dump 還是需要gdb..   太晚看到這個討論了 (泣

```
student@compiler-s20:~/src$ gdb --args parser test.p --dump-ast
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from parser...done.
(gdb) c
The program is not being run.
(gdb) run
Starting program: /home/student/src/parser single.p --dump-ast
warning: Error disabling address space randomization: Operation not permitted
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

Program received signal SIGABRT, Aborted.
0x00007f827cc25e97 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) backtrace
#0  0x00007f827cc25e97 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f827cc27801 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f827d27c957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f827d282ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f827d282b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f827d282d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f827d27e79f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f827d3172dd in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x000056151936fd02 in ConstantValueNode::ConstantValueNode (this=0x56151962a2b0, line=9, col=16, p_name=0x56151962a290 "0", p_type=0x561519371872 "integer",
    p_neg=0x0) at lib/AST/ConstantValue.cpp:13
#9  0x0000561519362c01 in yyparse () at parser.y:367
#10 0x0000561519365360 in main (argc=3, argv=0x7ffd33adce78) at parser.y:762
(gdb)
```
